### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi'

### ISSUE THREAD

**Issue by hy1080** [blackcon/VicunaWithGUI#2]
无论是在win10下还是在ubuntu20下都没有安装成功(The installation was not successful in both Win10 and Ubuntu 20)
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ai/VicunaWithGUI/llama-cpp-python/llama_cpp/server/__main__.py", line 22, in <module>
    from fastapi import Depends, FastAPI
ModuleNotFoundError: No module named 'fastapi'
```

**Comment by blackcon** [comment]
> 无论是在win10下还是在ubuntu20下都没有安装成功(The installation was not successful in both Win10 and Ubuntu 20)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/ai/VicunaWithGUI/llama-cpp-python/llama_cpp/server/__main__.py", line 22, in <module>
>     from fastapi import Depends, FastAPI
> ModuleNotFoundError: No module named 'fastapi'
> ```

@hy1080 
Thank you for sharing this issue.
I couldn't write down a few modules to install.
You can fix this issue by installing below modules.
```bash
# setup llama-cpp-python
cd llama-cpp-python
pip3 install scikit-build cmake
pip3 install fastapi sse_starlette uvicorn
python3 setup.py develop
```
